export type Rule = {
    is_quad: boolean,
    is_connect: boolean,
    is_lie: boolean,
    is_triple: boolean,
    is_out: boolean,
    is_dual: boolean,
    is_snake: boolean,
    is_balance: boolean,
    is_wall: boolean,
    is_neutral: boolean,
    is_xross: boolean,
    is_partial: boolean,
    is_eye: boolean,
}